//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillMapProject.Models
{
    using SkillMapProject.Controllers;
    using System;
    using System.Collections.Generic;

    public partial class Certification
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int SkillID { get; set; }
        public string Mark { get; set; }
        public string Result { get; set; }
        public Nullable<System.DateTime> NgayThiXacNhan { get; set; }
        public string NgayThiXacNhanStr
        {
            get
            {
                if (NgayThiXacNhan is DateTime date)
                {
                    return date.ToShortDateString();
                }
                else
                {
                    return "";
                }
            }
        }
        public Nullable<System.DateTime> NgayThiThucTe { get; set; }
        public string NgayThiThucTeStr
        {
            get
            {
                if (NgayThiThucTe is DateTime date)
                {
                    return date.ToShortDateString();
                }
                else
                {
                    return "";
                }
            }
        }
        public Nullable<int> NguoiChamDiem { get; set; }
        public int Updator { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string Note { get; set; }
        public Nullable<int> Sort { get; set; }
        public string Task { get; set; }
        public string TypeSkill { get; set; }
        public string Code { get; set; }
        public string CapDo { get; set; }
        public string NangCap { get; set; }
        public Nullable<System.DateTime> NgayNangCap { get; set; }
        public string NgayNangCapStr
        {
            get
            {
                if (NgayNangCap is DateTime date)
                {
                    return date.ToShortDateString();
                }
                else
                {
                    return "";
                }
            }
        }
        public string CNNguoiDaoTao { get; set; }
        public Nullable<System.DateTime> NgayCNNguoiDaoTao { get; set; }
        public string NgayCNNguoiDaoTaoStr
        {
            get
            {
                if (NgayCNNguoiDaoTao is DateTime date)
                {
                    return date.ToShortDateString();
                }
                else
                {
                    return "";
                }
            }
        }
        public Nullable<int> SoLanThi { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }

        public virtual Member Member { get; set; }
        public virtual Member Member1 { get; set; }
        public virtual Member Member2 { get; set; }
        public virtual Skill Skill { get; set; }

        public string LevelCurrent
        {
            get
            {
                string level = "";
                // Cả 3 cùng có thì lấy Level III
                if (Ultils.IsNull(CNNguoiDaoTao) && Ultils.IsNull(NangCap) && Ultils.IsNull(CapDo))
                {
                    level = CNNguoiDaoTao;
                }

                // Level III = null thì lấy Level II
                else if (!Ultils.IsNull(CNNguoiDaoTao) && Ultils.IsNull(NangCap) && Ultils.IsNull(CapDo))
                {
                    level = NangCap;
                }

                // Level III & II = null thì lấy Level I
                else if (!Ultils.IsNull(CNNguoiDaoTao) && !Ultils.IsNull(NangCap) && Ultils.IsNull(CapDo))
                {
                    level = CapDo;
                }

                // Level III & I = null thì lấy Level II
                else if (!Ultils.IsNull(CNNguoiDaoTao) && Ultils.IsNull(NangCap) && !Ultils.IsNull(CapDo))
                {
                    level = NangCap;
                }
                else if (Ultils.IsNull(CNNguoiDaoTao) && Ultils.IsNull(NangCap) && !Ultils.IsNull(CapDo))
                {
                    level = CNNguoiDaoTao;
                }
                return level;
            }
        }
        public DateTime? LevelDateCurrent { get; set; }


        /// <summary>
        /// Ngày cấp hiện tại
        /// </summary>
        public DateTime? CurrentGrantDate
        {
            get
            {
                DateTime current = new DateTime();
                if ((NgayCNNguoiDaoTao != null) && (NgayNangCap != null) && (NgayCap != null))
                {
                    current = (DateTime)NgayCNNguoiDaoTao;
                }
                else if ((NgayCNNguoiDaoTao == null) && (NgayNangCap != null) && (NgayCap != null))
                {
                    current = (DateTime)NgayNangCap;
                }

                else if ((NgayCNNguoiDaoTao == null) && (NgayNangCap == null) && (NgayCap != null))
                {
                    current = (DateTime)NgayCap;
                }
                else if ((NgayCNNguoiDaoTao == null) && (NgayNangCap != null) && (NgayCap == null))
                {
                    current = (DateTime)NgayNangCap;
                }
                else if ((NgayCNNguoiDaoTao != null) && (NgayNangCap != null) && (NgayCap == null))
                {
                    current = (DateTime)NgayCNNguoiDaoTao;
                }
                return current;
            }
        }

        public string CurrentGrantDateStr
        {
            get
            {
                return CurrentGrantDate is DateTime DateStr ? DateStr.ToShortDateString() : "";
            }
        }
    }
}
