//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillMapProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_Department
    {
        public string DeptCode { get; set; }
        public string DeptName { get; set; }
        public string TypeOf { get; set; }
        public string InputPerson { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
        public string ModifyPerson { get; set; }
        public Nullable<System.DateTime> Modifydate { get; set; }
    }
}
