//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillMapProject.Models
{
    using SkillMapProject.Controllers;
    using System;
    using System.Collections.Generic;

    public partial class OLYMPIC
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Code { get; set; }
        public string TestContent { get; set; }
        public Nullable<int> TestNumber { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public string TestDateStr
        {
            get
            {
                if(TestDate is DateTime date)
                {
                    return date.ToDateString();
                }
                else
                {
                    return "";
                }
            }
        }
        public string TestResult { get; set; }

        public virtual Member Member { get; set; }

    }
}
